---

- name: "configuration play." 

  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_host_key_checking: false   # to skip the user confirmation on SSH authentication

  pre_tasks:
  - name: "wait 600 seconds for target connection to become reachable/usable."
    shell: sleep 20
  - name: "install python for Ansible."
    shell: echo "test!"
      # Your code here
  roles:
  - configure-server